version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ageresult"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hcff74ukfhft"
s3_prefix = "ageresult"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

